### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by 4Seasons11** [xXSchrandXx/SpigotPlugins#1]
[20:02:03 WARN]: [AsyncWorldManager] Task #114 for AsyncWorldManager v0.1.0-SNAPSHOT generated an exception
 java.lang.NoSuchMethodError: org.bukkit.World.setHardcore(Z)V
        at de.xxschrandxx.awm.api.config.WorldConfigManager$1.run(WorldConfigManager.java:460) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by xXSchrandXx** [comment]
Wich minecraft Version do you use?

**Comment by xXSchrandXx** [comment]
You could try the latest [snapshot](https://xxschrandxx.github.io/SpigotPlugins/AsyncWorldManager/0.1.0-SNAPSHOT/AsyncWorldManager-0.1.0-SNAPSHOT.jar).

**Comment by xXSchrandXx** [comment]
Or you can use the latest release: https://www.spigotmc.org/resources/async-worldmanager-awm.58943/update?update=315951

**Comment by xXSchrandXx** [comment]
Redownload the latest snapshot, I fixxed it with commut [192730a](https://github.com/xXSchrandXx/SpigotPlugins/commit/192730a4bacf9f82d464cf3a4d3e9f32b7a4ded9).
